package com.walking.meeting.dataobject.dto;

import java.util.Date;

public class UserDTO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.id
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.username
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.password
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.email
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.question
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    private String question;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.answer
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    private String answer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.role
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.create_time
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.update_time
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_test.delete_time
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    private Date deleteTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.id
     *
     * @return the value of user_test.id
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.id
     *
     * @param id the value for user_test.id
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.username
     *
     * @return the value of user_test.username
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.username
     *
     * @param username the value for user_test.username
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.password
     *
     * @return the value of user_test.password
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.password
     *
     * @param password the value for user_test.password
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.email
     *
     * @return the value of user_test.email
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.email
     *
     * @param email the value for user_test.email
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.question
     *
     * @return the value of user_test.question
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public String getQuestion() {
        return question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.question
     *
     * @param question the value for user_test.question
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.answer
     *
     * @return the value of user_test.answer
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.answer
     *
     * @param answer the value for user_test.answer
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public void setAnswer(String answer) {
        this.answer = answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.role
     *
     * @return the value of user_test.role
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.role
     *
     * @param role the value for user_test.role
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.create_time
     *
     * @return the value of user_test.create_time
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.create_time
     *
     * @param createTime the value for user_test.create_time
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.update_time
     *
     * @return the value of user_test.update_time
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.update_time
     *
     * @param updateTime the value for user_test.update_time
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_test.delete_time
     *
     * @return the value of user_test.delete_time
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_test.delete_time
     *
     * @param deleteTime the value for user_test.delete_time
     *
     * @mbg.generated Sun Oct 27 13:24:11 CST 2019
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }
}